In [9]:
#Question 1
import numpy as np
a = np.array([2,3,2,2,2,1])
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1
print(b)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [12]:
#Question 2
import numpy as np
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[np.logical_not(np.isnan(a))]
print(a)

[1. 2. 3. 5. 6. 7.]


In [16]:
#Question 3
import numpy as np
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
indexes=[]
for i in range(0,len(a)):
    if i>0 and i<len(a)-1 and a[i]>a[i-1] and a[i]>a[i+1]:
        indexes.append(i)
print(indexes)

[2, 5]


In [21]:
#Question 4
w = int(input("Enter Window size= "))
s = int(input("Enter stride size= "))
a = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
array = []
cur=0
for i in range(0,12,2):
    l=[]
    for j in range(0,w):
        l.append(a[i+j])
    array.append(l)
array
    
    

Enter Window size= 4
Enter stride size= 2


[[0, 1, 2, 3],
 [2, 3, 4, 5],
 [4, 5, 6, 7],
 [6, 7, 8, 9],
 [8, 9, 10, 11],
 [10, 11, 12, 13]]