In [3]:
#Question 1
import numpy as np
  

x = np.array([0, 56, 89,23, 69, 980,567])

print(x)
  
if np.all(x):
    print("No zero Present")
else :
    print("Zero Present")

[  0  56  89  23  69 980 567]
Zero Present


In [5]:
#Question 2
import numpy as np
#Passing marks = 33
marks = np.array([30, 25, 89,  23, 69, 98,67,52,35,18])
new_marks=[]
tot=0
for i in marks:
    if i>=33:
        new_marks.append(i)
        tot+=i
mean=tot/len(new_marks)
sorted(new_marks)
median = new_marks[len(new_marks)//2]
print("Mean:",mean)
print("Median:",median)

Mean: 68.33333333333333
Median: 67


In [8]:
#Question 4
import numpy as np
arr2D = np.array([[11, 12, 13, 22],
                  [21, 7, 23, 14], 
                  [31, 10, 33, 7]])


columnIndex = 1
# Sort 2D numpy array by 2nd Column
sortedArr = arr2D[arr2D[:,columnIndex].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

Sorted 2D Numpy Array
[[21  7 23 14]
 [31 10 33  7]
 [11 12 13 22]]
